### PR TITLE
Split web.py

### PR DESCRIPTION
**Pull request by asvetlov**
Try to split huge web.py into smaller modules.

@fafhrd91 if you like the way I can move forward.

### CODE REVIEW

**Comment by fafhrd91** [comment]
lgtm

**Comment by ludovic-gasc** [comment]
Small suggestion: instead of to prefix all files by web_, you should create a folder: web
web.py should be **init**.py file in this new folder.

**Comment by asvetlov** [comment]
IIRC @fafhrd91 want to have flat file structure.

**Comment by kxepal** [comment]
@GMLudo +1, subpackage aiohttp.web sounds to be better idea for module split.

**Comment by ludovic-gasc** [comment]
This discussion is more religious that technical, but yes, at least for me, it will be more clear to have aiohttp.web in a folder.

**Comment by fafhrd91** [comment]
Flat.
-10 for sub package

**Comment by ludovic-gasc** [comment]
For my understanding, is it possible to know your arguments in favor of a flat design ?

**Comment by fafhrd91** [comment]
It is just easier to observe what package has.

**Comment by fafhrd91** [comment]
@asvetlov maybe we should use '**all**' for web_xxx modules?

**Comment by asvetlov** [comment]
@fafhrd91 sorry, I don't follow your suggestion. Where do you want to put '**all**'?

**Comment by klen** [comment]
Already done, but my opinion is also +1 to subpackage.

**Comment by fafhrd91** [comment]
@asvetlov
1. i think web_ws.py should be part of web_reqrep.py
2. also i think web_app.py should be web.py 
3. web_exceptions.py should have `__all__`, and web.py should use web_exceptions.**all** instead of explicit list

**Comment by fafhrd91** [comment]
changed

**Comment by asvetlov** [comment]
@fafhrd91 ok with moving web_app back to web.py and `__all__` usage.

You have broken flake8 checks BTW. 
I'd like to keep code base in good state for pep8 and pyflakes checkers.
Would you repair the problem or let me make a fix?

**Comment by fafhrd91** [comment]
What version of flake do you use?
What error do you get? My tests passes

**Comment by asvetlov** [comment]
Sorry, I have had pep8 1.5.
pep8 1.6 has fixed regression from 1.5.

**Pull request merged**
