### PR TITLE
http pipelining

### PR DESCRIPTION
**Pull request by fafhrd91**
@asvetlov @kxepal

### CODE REVIEW

**Comment by kxepal** [comment]
Wow! That's great! Will be happy to test this.

**Comment by fafhrd91** [comment]
It doesn't give any increase in plain requests. It may give some increase if you do extra io in handlers. This shows that slow part is not in protocol write track, it is probably whole aiohttp.web stack is slightly slow

**Comment by fafhrd91** [comment]
so on "ok" responses pipelining is ~5% slower than non-pipelining mode.
i think i can speed it up by refactoring request parsing.

**Comment by fafhrd91** [comment]
merged to master

**Comment by fafhrd91** [comment]
I did some more optimizations, now it starting look better

Env: uvloop, -OO, no logs

1.2 ~7.4k rps
1.4a ~9.8k rps
1.4a pipelining ~11.7k rps

**Comment by kxepal** [comment]
Meanwhile it seems that HTTP/1 Pipelining is going to be deprecated: https://bugzilla.mozilla.org/show_bug.cgi?id=1340655

**Pull request closed without merging**
