### PR TITLE
Add number of bytes to stream.read_nowait

### PR DESCRIPTION
**Pull request by eyal-stratoscale**

### CODE REVIEW

**Comment by fafhrd91** [comment]
what is the reason?

**Comment by eyal-stratoscale** [comment]
The private method accepts number of bytes, I don't understand why the public one shouldn't expose this feature.
plus, I need this feature :-)

**Comment by eyal-stratoscale** [comment]
@fafhrd91 , can you please merge this pull request?

**Comment by fafhrd91** [comment]
Sure

**Comment by eyal-stratoscale** [comment]
Thanks

**Pull request merged**
