### PR TITLE
Resolved #986 - implemented router shortcuts

### LINKED ISSUE #986: Implement router shortcuts
Add `router.add_get`, `router.add_post` and others.

### PR DESCRIPTION
**Pull request by alexm92**
## What do these changes do?

Added shortcut methods for router.

## Are there changes in behavior for the user?

New methods for adding routes: `add_get`, `add_post`, `add_put`, `add_patch`, `add_delete`

## Related issue number

#986 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes

### CODE REVIEW

**Comment by alexm92** [comment]
Hey, did unittest only for `add_get`, should I do also for other methods? It's copy & pasteing

**Comment by asvetlov** [comment]
Having methods which are not test covered is a very bad idea.

Also documentation update is required.

**Comment by alexm92** [comment]
@asvetlov added other unittests and documentation :)

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
