### PR TITLE
Fix body_length/output_length for StreamResponse after eof.

### PR DESCRIPTION
**Pull request by singulared**
## What do these changes do?

After #1663 body length attribute is broken if eof received.

## Are there changes in behavior for the user?

Nope

## Related issue number

Nope

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by fafhrd91** [comment]
I fixed `body_part` already, let's not change anything else

**Comment by fafhrd91** [comment]
Sorry, let's not change anything else

**Comment by singulared** [comment]
I already seen you fix, btw i add test for body_length and remove deprecated self.started from StreamResponse.\_\_repr\_\_.
So, as you wish. (:

**Comment by fafhrd91** [comment]
This changes are not for 1.3

**Comment by singulared** [comment]
Ok. Closed.

**Pull request closed without merging**
