### PR TITLE
Add more headers per RFC: 2616, 2518, 3230, 5988 and for event source

### PR DESCRIPTION
**Pull request by kxepal**
Added all headers defined in RFC2616;
Fixed Trailers one - there is no such, but Trailer;
Added Digest from 3230 as successor of Content-MD5;
Since aiohttp knows about COPY method, it need to know about Destination from 2518;
Link from 5988 is quite useful for hypermedia;
Last-Event-Id from Event Source spec...because I use it P:

All headers are sorted by name.

### CODE REVIEW

**Comment by fafhrd91** [comment]
Lgtm

**Comment by fafhrd91** [comment]
@kxepal you should run tests, fix TRAILERS in protocol.py

**Comment by kxepal** [comment]
Yea, I noticed that already /:
Extracted Trailers rename into separate commit to explicitly define that change.

**Comment by kxepal** [comment]
All looks good now. Meanwhile have found origin on Trailers: http://tools.ietf.org/html/rfc2616#section-13.5.1 - it's only mentioned ones in whole spec with no description and looks like a typo since everywhere else Trailer is used.

**Comment by fafhrd91** [comment]
Seems you are wrong
http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html#sec13.5.1

**Comment by kxepal** [comment]
@fafhrd91 that is the only place in whole spec where Trailers is mentioned. Not in updates nor successor it does not. So it looks like a typo.

**Comment by kxepal** [comment]
http://www.w3.org/Protocols/HTTP/1.1/rfc2616bis/issues/#i9

**Comment by fafhrd91** [comment]
I don't think so, but anyway here is what I found
http://lists.w3.org/Archives/Public/ietf-http-wg/2014JulSep/1710.html
interesting staff regarding hop headers.

I think we can remove hop headers support at all, we are not wsgi or proper
proxy.

@asvetlov btw in that way we can implement custom aiohttp.web chunked
encoding

**Comment by kxepal** [comment]
@fafhrd91 you don't trust w3.org bug tracker?(:

Removing support of these headers isn't correct. For instance, same Trailer is very useful for chunked transfer to pass some data, like content length or md5 hash, after streaming big binary blob is done without need to iterate over it for twice on the server side.

**Comment by fafhrd91** [comment]
That just means we gives ability to add those headers to developer, that's
it. Developer can send any headers. We just a way to easily add chunking
and compression but only in a form of helpers.

**Pull request merged**
