### PR TITLE
Fixing keep-alive

### PR DESCRIPTION
**Pull request by gabtremblay**
Upon testing and touroughly reviewing tcpdump output, it appeared that the client keep-alive functionality was broken, creating a new socket for each request. This patch puts it back in place with minimal test edit.

### CODE REVIEW

**Comment by asvetlov** [comment]
Please fix pep8 error from Travis build

**Comment by asvetlov** [comment]
I feel you PR is perfect but we need stronger test for keepalives.
Would you add functional test?

Scenario is:
1. Create aiohttp web server with keepalives enabled. I suggest to use `aiohttp.web` instead of domestic server used in `test_client_functional.py`. New test file is good -- call it `test_client_functional_newstyle.py` for example.
2. Make keepalive request.
3. Make sure connection is in the connector after releasing response object.

**Comment by gabtremblay** [comment]
Good point.

**Comment by asvetlov** [comment]
Thanks a lot!

**Comment by gabtremblay** [comment]
NP, my pleasure.

**Comment by mpaolini** [comment]
I think this patch is wrong. Without it I see sockets correclty reused; with it I see single transports/sockets being used by two separate coroutines

**Pull request merged**
