### PR TITLE
Fix #271: Memory leak in request

### LINKED ISSUE #271: Memory leak in request
Hi all,

 Since I upgraded to 0.14.4 (from 0.9.0)  I am experiencing memory leaks in a Dropbox-API longpoller. It is a single process that spawns a few thousands of greenlets. Each greenlet performs a `request()`, that blocks for 30 seconds, then parses the response and dies. Then a new greenlet is spawned.

I am running on python 3.4.0, Ubuntu 14.04. I use the connection pool feature, passing the same connector singleton to each `.request()` call.

I played with tracemalloc, dumping a `<N>.dump` stat file every minute and found out that the response parser instances keep increasing in number (look at the third line of each stat)

```
root@9330490eafc9:/src# python3 -c "import pprint; import tracemalloc; pprint.pprint(tracemalloc.Snapshot.load('5.dump').statistics('lineno')[:3])"
[<Statistic traceback=<Traceback (<Frame filename='/usr/lib/python3.4/ssl.py' lineno=648>,)> size=6130540 count=82650>,
 <Statistic traceback=<Traceback (<Frame filename='<frozen importlib._bootstrap>' lineno=656>,)> size=3679906 count=31688>,
 <Statistic traceback=<Traceback (<Frame filename='/usr/local/lib/python3.4/dist-packages/aiohttp/parsers.py' lineno=198>,)> size=2176408 count=4437>]
root@9330490eafc9:/src# 
root@9330490eafc9:/src# 
root@9330490eafc9:/src# python3 -c "import pprint; import tracemalloc; pprint.pprint(tracemalloc.Snapshot.load('6.dump').statistics('lineno')[:3])"
[<Statistic traceback=<Traceback (<Frame filename='/usr/lib/python3.4/ssl.py' lineno=648>,)> size=6130476 count=82649>,
 <Statistic traceback=<Traceback (<Frame filename='<frozen importlib._bootstrap>' lineno=656>,)> size=3679906 count=31688>,
 <Statistic traceback=<Traceback (<Frame filename='/usr/local/lib/python3.4/dist-packages/aiohttp/parsers.py' lineno=198>,)> size=2199704 count=4463>]
root@9330490eafc9:/src# 
root@9330490eafc9:/src# 
root@9330490eafc9:/src# python3 -c "import pprint; import tracemalloc; pprint.pprint(tracemalloc.Snapshot.load('7.dump').statistics('lineno')[:3])"
[<Statistic traceback=<Traceback (<Frame filename='/usr/lib/python3.4/ssl.py' lineno=648>,)> size=6130476 count=82649>,
 <Statistic traceback=<Traceback (<Frame filename='<frozen importlib._bootstrap>' lineno=656>,)> size=3679906 count=31688>,
 <Statistic traceback=<Traceback (<Frame filename='/usr/local/lib/python3.4/dist-packages/aiohttp/parsers.py' lineno=198>,)> size=2231064 count=4498>]
```

tracemalloc reports this stack trace:

```
python3 -c "import pprint; import tracemalloc; pprint.pprint(tracemalloc.Snapshot.load('3.dump').filter_traces([tracemalloc.Filter(True, '*aiohttp/parsers.py')]).statistics('traceback')[0].traceback.format())"
['  File "/usr/local/lib/python3.4/dist-packages/aiohttp/parsers.py", line '
 '198',
 '    p = parser(output, self._buffer)',
 '  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 633',
 '    httpstream = self._reader.set_parser(self._response_parser)',
 '  File "/usr/local/lib/python3.4/dist-packages/aiohttp/client.py", line 108',
 '    yield from resp.start(conn, read_until_eof)',
 '  File "/src/xxxxxx/main.py", line 70',
 '    connector=LONGPOLL_CONNECTOR',
```

Looks like there is something keeping alive those parsers....

Using `force_close=True` on the connector makes no difference.

Then I tried calling `gc.collect()` after every single request, and is going much better ~~but the leak has not~~ the leak **has** disappeared completely-. This means (maybe is an unrelated issue) the library creates more reference cycles thant the CGC can handle.

It my well be my own bug, or maybe something to do with python 3.4.0 itself. I'm still digging into it.

### PR DESCRIPTION
**Pull request by asvetlov**

### CODE REVIEW

**Comment by fafhrd91** [comment]
why do you think `add_headers()` is the problem?

**Comment by asvetlov** [comment]
It is not `add_headers()` actually but generator unpacking.
See https://gist.github.com/asvetlov/227af16ae9eb38db7f22
We discovered the issue with @mpaolini last night.

Regarding to `add_headers()` -- it's just extra call which doesn't make any additional value.

**Comment by fafhrd91** [comment]
ok, i see.

**Comment by kxepal** [comment]
@asvetlov Nice found! Is that CIMultiDict specific or general generator unpacking issue don't you know?

**Comment by asvetlov** [comment]
It's python unpacking issue.
Reproducible with any structure (dict, list, etc.).
I'm trying to investigate and maybe create a patch.

**Comment by mpaolini** [comment]
It did fix the leak that has been going on on my side since v0.14.0 at least. Thanks @asvetlov

**Pull request merged**
