### PR TITLE
Fix typos in documentation

### PR DESCRIPTION
**Pull request by jwilk**
Found using [mwic](http://jwilk.net/software/mwic) and [anorack](https://github.com/jwilk/anorack).

### CODE REVIEW

**Comment by asvetlov** [comment]
Cool!
Would you make another PR for adding `make spell` command for spell checking?
We could even integrate spell check into travis-ci run, I believe it makes sense.

**Comment by jwilk** [comment]
`make doc-spelling` already exists, but apparently nobody has run it for a very long time.
I'll try to knock it into shape. :)

**Comment by f0t0n** [comment]
`make doc-spelling` doesn't work for me locally. Should we add `sphinxcontrib-spelling` to requirements-ci.txt?

**Comment by asvetlov** [comment]
Hmm. it's tricky.

I use Ubuntu for local test runs but macosx people had blamed the `enchant` is not  available in their OS.

That's why we have removed `sphinxcontrib-spelling` from requirements.

**Pull request merged**
