### PR TITLE
Fix connection pooling

### PR DESCRIPTION
**Pull request by mpaolini**
Fixes weirdness introduced in #254 and #254 and later in #406 .

Supersedes #471 

See commit messages for more details

### CODE REVIEW

**Comment by kxepal** [comment]
Nice found! But can we have any test to prove that this wouldn't be broken in future?

**Comment by mpaolini** [comment]
I did add a specific test and fixed a few existing bous ones, let's see what the buildbots say

**Comment by mpaolini** [comment]
I am testing this in staging now and solves all the that came out upgrading from 0.14.x to 0.17.2

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/aiohttp/client.py", line 135, in request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.4/site-packages/aiohttp/client_reqrep.py", line 566, in start
    self.message = yield from httpstream.read()
  File "/usr/local/lib/python3.4/site-packages/aiohttp/streams.py", line 505, in read
    result = yield from super().read()
  File "/usr/local/lib/python3.4/site-packages/aiohttp/streams.py", line 365, in read
    yield from self._waiter
  File "/usr/local/lib/python3.4/asyncio/futures.py", line 386, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.4/asyncio/tasks.py", line 287, in _wakeup
    value = future.result()
  File "/usr/local/lib/python3.4/asyncio/futures.py", line 275, in result
    raise self._exception
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  [my code here]
  File "/usr/local/lib/python3.4/site-packages/aiohttp/client.py", line 286, in get
    **kwargs)
  File "/usr/local/lib/python3.4/site-packages/aiohttp/client.py
```

**Comment by tdryer** [comment]
+1, this fixes certain requests consistently timing out in my application starting with aiohttp 0.17.0.

**Comment by fafhrd91** [comment]
+1, those ServerDisconnectedError exceptions are very annoying

**Comment by fafhrd91** [comment]
Thanks!

i'll test changes and then will do new bug fix release

**Comment by mpaolini** [comment]
You are welcome! I've tested this on staging for a week now and it works all right

**Pull request merged**
