### PR TITLE
Issues about #1025 and #1044

### PR DESCRIPTION
**Pull request by Taekyoon**
## What do these changes do?

#1025 add two parameters to ws_connect : proxy, proxy_auth
#1044 added a function make_netloc because of the host data size problem.

## Related issue number

#1025 
#1044 

## Checklist

- [ V ] I think the code is well written
- [ V ] Unit tests for the changes exist
- [ ] Documentation reflects the changes

### CODE REVIEW

**Comment by asvetlov** [comment]
I'm sorry but I remember you have some tests.
Did you forget to include them?

**Comment by Taekyoon** [comment]
I'll check right now

나의 iPhone에서 보냄
1. 8. 15. 오후 10:54 Andrew Svetlov notifications@github.com 작성:

**Comment by Taekyoon** [comment]
I'm sorry Andrew..

Test method is missing.
but I can make this again.
I'll pull request right again.

2016-08-15 23:23 GMT+09:00 Choi Taekyoon tgchoi03@gmail.com:

**Comment by Taekyoon** [comment]
I Added 3 test functions about #1044.

**Comment by Taekyoon** [comment]
I checked some problem from flake.
And I fixed it.

**Comment by asvetlov** [comment]
Thanks!

**Comment by Taekyoon** [comment]
Me either!!
I really thank you because you taught me how to commit the project.
This experience would be useful to my future activity.
Thank you so much!

**Pull request merged**
