### PR TITLE
Improve speed of native WebSocket frame parsing

### PR DESCRIPTION
**Pull request by SethMichaelLarson**
## What do these changes do?

Improve speed for native parsing WebSocket frames using faster bit-manipulation and constants. Doesn't require any new documentation/unit-tests.

## Are there changes in behavior for the user?

No changes in behavior.

## Related issue number

No issues are closed with this PR.

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist (Not needed?)
- [ ] Documentation reflects the changes (Not needed?)
- [x] Add yourself to `CONTRIBUTORS.txt`
- [x] Add a new entry to `CHANGES.rst`

### CODE REVIEW

**Comment by asvetlov** [comment]
1. I like using hex numbers for bits, masks etc. Why did you replace them with decimals?
2. What is speed improvement? Do you have any benchmark?

**Comment by sethmlarson** [comment]
@asvetlov I will change the decimal back to hex. 
The other changes are just using bit arithmetic instead of integer arithmetic. Simple timeit tests can show that this is substantially faster.

**Comment by asvetlov** [comment]
If the difference is huge -- please provide a benchmark for the function.
I doubt that integer arithmetic is slower that bit based on current CPU.

**Comment by sethmlarson** [comment]
The test that failed in Travis is an asyncio timeout test, not anything related to WebSockets.
You're right that the difference isn't huge, but free cycles are still free cycles.

Tested on an Intel Xeon X5650 6 x 2.67GHz
Before:

```
$ python3.5 -m timeit -s 's = 30' 's // 4'
10000000 loops, best of 3: 0.0644 usec per loop

$ python3.5 -m timeit -s 's = 3289475' 's % 4'
10000000 loops, best of 3: 0.0662 usec per loop
```

After:

```
$ python3.5 -m timeit -s 's = 30' 's >> 2'
10000000 loops, best of 3: 0.0549 usec per loop

$ python3.5 -m timeit -s 's = 3289475' 's & 3'
10000000 loops, best of 3: 0.0586 usec per loop
```

17% speed-up for // vs. >> and 12% speed-up for % vs. &

**Comment by asvetlov** [comment]
I mean the benchmark for the whole `parse_frame`, not single math operation only.
Maybe rewriting with cython will make a value but your change is just invisible.

**Pull request closed without merging**
