### PR TITLE
make chunked transfer encoding explicit

### PR DESCRIPTION
**Pull request by fafhrd91**
@asvetlov 

1. hop headers removed, there is no any reason to cut them off, aiohttp is a framework
2. chunked encoding is explicit
3. wsgi behave same as before

### CODE REVIEW

**Comment by fafhrd91** [comment]
we may rename "enable_chunked_encoding" to something else

**Comment by asvetlov** [comment]
Let me review the PR for tomorrow, please.

**Comment by fafhrd91** [comment]
ok, np

**Comment by asvetlov** [comment]
I like the changes but cannot find `.add_chunking_filter()` call in server code at all (both in master and the PR).

**Comment by fafhrd91** [comment]
We use it from client only, let's refactor this next time

**Comment by asvetlov** [comment]
Ok

**Comment by asvetlov** [comment]
LGTM

**Comment by fafhrd91** [comment]
Actually we can use filters on server side as well.  Signature for Web response method could be 'enable_chunked_encoding(chunk_size=8192)' and 'enable_compression()'

**Comment by asvetlov** [comment]
Agree. Would do you like to add those methods in this PR?

**Comment by fafhrd91** [comment]
Will do

**Comment by fafhrd91** [comment]
Yes, will do

**Comment by fafhrd91** [comment]
@asvetlov i added chunk size and compression to web.StreamResponse
but for compression there should be application level configuration for compression enabling, call enable_compression for each response sounds not very good.

**Pull request merged**
