### PR TITLE
Use a mmap file to read data in StaticRoute

### PR DESCRIPTION
**Pull request by jashandeep-sohi**
When making use of the fallback sendfile method, a `mmap` file should be used to read the data to reduce memory usage.

Correct me if I'm wrong, but I believe reading data from a `mmap` file is better if you are running a web app on multiple processes. With a `mmap` file each process can share the memory pages, and thus save you some memory. This probably only true for large files.

### CODE REVIEW

**Comment by asvetlov** [comment]
I think it's overoptimization.
Most likely in production configuration the code will be run on Linux with sendfile support (and behind nginx BTW).
Don't expect too much from mmap support.

**Comment by jashandeep-sohi** [comment]
I'm sure there are countless schemes of serving up static content using other software, but I was strictly thinking from aiohttp's point of view rather than aiohttp + x.

But sendfile is useless in my case because I'm serving everything over SSL. I know I can do SSL termination at the load balancer, but I'd rather have each app do it's own crypto.

I'll do some benchmarks tonight to see if using `mmap` files makes any practical difference.

**Comment by asvetlov** [comment]
SSL use case makes sense for PR, I've missed this.

**Comment by asvetlov** [comment]
@jashandeep-sohi unfortunately GitHub doesn't send notification email if you just push new commits without a comment.
So I'm not aware about your work on the PR.

Do you think the current stage is ready for review?

**Comment by jashandeep-sohi** [comment]
Well, I was trying to running some benchmarks yesterday with `ab` (Apache HTTP server benchmarking tool), but I encountered a possible bug with `Keep-Alive` connections so I got side-tracked with that. I'll make a new issue to discuss that.

As for this PR, the code is good, but I haven't profiled memory usage yet.

**Comment by jashandeep-sohi** [comment]
Consider reviewing & merging.

**Comment by asvetlov** [comment]
Please fix merge conflicts

**Comment by jashandeep-sohi** [comment]
fixed

**Comment by asvetlov** [comment]
Thanks

**Pull request merged**
