### PR TITLE
Note that aiohttp.web can be used in production

### LINKED ISSUE #234: Add note about production deployment
Users of the aiohttp server coming from bottle or flask may be concerned about performance and deployment (both bottle and flask have sections called "Deployment" or similar). If aiohttp's web server is fine to use in production, perhaps a note could be added to state this?

I'd be willing to perform a simple benchmark (against, say, cherrypy) but I suspect this has already been done. Has it?

For reference, this is the deployment section for bottle: http://bottlepy.org/docs/dev/deployment.html

### PR DESCRIPTION
**Pull request by ariddell**
Users coming from Flask, Django, and Bottle anticipate special
instructions about deployment. Closes #234.

### CODE REVIEW

**Comment by asvetlov** [comment]
Sorry, no. 

`aiohttp` is not _multi-threaded_ but it is **asynchronous**.

That means the `aiohttp` (as well as `asyncio`) has lightweight tasks, which are executed in _parallel_ by _event loop_.

 _Tornado_ and _Twisted_ does the same (in not so user-friendly manner).

_gevent_ and _eventlet_ have a different way, both uses `greenlet` technique -- but they are also single-threaded with lightweight threads.

**Comment by ariddell** [comment]
You're right of course. I forgot asyncio used lightweight tasks. Updated.

**Comment by asvetlov** [comment]
Is your point that `aiohttp.web` is a webserver itself and does not requires any WSGI proxies?

But for production you are likely need to hide your server under _reverse proxy / load balancer_ umbrella.

So your tip should have a link to "Deployment" chapter (not present for now, but you may create `./docs/deployment.rst` for those).

**Comment by ariddell** [comment]
Yes -- that's what I'm trying to get at. You _just_ need a reverse proxy, no WSGI wrapper à la bottle/flask/django. I think we're talking about the same thing.

I didn't realize there was a Deployment chapter -- I think such a chapter would eliminate the need for this PR.

**Comment by asvetlov** [comment]
Deployment chapter is absent.

You are the first person who asked for this.

If you would like to create `./docs/deployment.rst` and write _Deployment instructions_ --- your are welcome.

If not -- I'll do it sometimes.

Anyway, thanks for request.

**Comment by fafhrd91** [comment]
I think we should add paste deploy template

**Comment by asvetlov** [comment]
+1

On Wed, Jan 14, 2015 at 6:45 PM, Nikolay Kim notifications@github.com
wrote:

> I think we should add paste deploy template
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KeepSafe/aiohttp/pull/237#issuecomment-69947242.

## 

Thanks,
Andrew Svetlov

**Comment by asvetlov** [comment]
close as stale

**Comment by richardolsson** [comment]
Arrived here after having searched for best practices for deploying and running aiohttp in production. Does anyone have any pointers, articles I should read, projects I should look up et c?

**Comment by ludovic-gasc** [comment]
@richardolsson: Not real doc, the stuff more closer as production environnement is API-Hour starter kit: https://github.com/Eyepea/cookiecutter-API-Hour
It's API-Hour+aiohttp.web oriented, nevertheless, the config files are interesting for a production usage: https://github.com/Eyepea/cookiecutter-API-Hour/tree/master/%7B%7Bcookiecutter.app_name%7D%7D/etc
Especially init.d script and logrotate config file.

**Comment by fafhrd91** [comment]
I use gunicorn+pastedeploy with aiohttp.web worker. There are plenty of documentation how to deploy with pastedeploy

**Pull request closed without merging**
