### PR TITLE
Fixed misses in helpers

### PR DESCRIPTION
**Pull request by AraHaan**
This commit fixes all 4 of the misses in helpers.py.

## What do these changes do?

Fix the Misses in helpers.py

## Are there changes in behavior for the user?

No changes in behavior at all.

## Related issue number

None

## Checklist

- [x] Unit tests for the changes exist
- [x] I think the code is well written

### CODE REVIEW

**Comment by AraHaan** [comment]
@fafhrd91 What you think of this PR? Also I noticed there was a missing 0 in the version so I fixed that as well in this PR, btw you could also look in #1518 as well to. It also contains my entry in ``CONTRIBUTORS.txt``

**Comment by fafhrd91** [comment]
i don't think it worth to create new module just for import checks.
also it seems nothing uses `check_loop`

**Comment by AraHaan** [comment]
So, Check loop can be safely removed. I see.

**Comment by AraHaan** [comment]
Ok, then check_loop has now been removed completely since it is not getting used anyway so yeah.

**Comment by AraHaan** [comment]
hmm if only asyncio had that get_future instead. hmmm

**Comment by fafhrd91** [comment]
I leave this PR to @asvetlov
He is active maintainer

**Comment by AraHaan** [comment]
Ok, found a way to help get what we need. Using ``getattr`` for if ``asyncio.ensure_future`` does not exist it returns ``asyncio.async`` and use 1 line.

ss 2016-12-30 at 04 02 04

**Comment by AraHaan** [comment]
Looks like I just had to monkey patch 1 of the tests as sometimes it would fail at ``web.run_app`` hmm but is more often then not rare. So, when it happens should make it instead of the ``pass`` that I am doing right now to make it ``xfail``

**Comment by asvetlov** [comment]
I've dropped `check_loop` and fixed version number. 39b8568
`ensure_future` is covered by running on different python versions.

**Pull request closed without merging**
