### PR TITLE
Fix #758: Handle empty body with gzipped encoding

### LINKED ISSUE #758: Empty body handled as error (204 No Content)
An empty body handled as error. Although it isn't error. I see aiohttp code, it always trying to decompress empty data and raised.

```
Traceback (most recent call last):
  File "example.py", line 22, in <module>
    fetch_page(rh))
  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 342, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(value)
  File "example.py", line 8, in fetch_page
    print(await Bucket(client, 'ololo').delete('XXXX'))
  File "/usr/home/vg/Develop/aiohttp_riak/aiohttp_riak/Bucket.py", line 100, in delete
    return False
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/client.py", line 523, in __aexit__
    yield from self._resp.release()
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 656, in release
    chunk = yield from content.readany()
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/streams.py", line 472, in wrapper
    result = yield from func(self, *args, **kw)
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/streams.py", line 535, in readany
    return (yield from super().readany())
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/streams.py", line 265, in readany
    raise self._exception
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/parsers.py", line 189, in set_parser
    next(p)
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/protocol.py", line 313, in __call__
    out.feed_eof()
  File "/usr/home/vg/Develop/aiohttp_riak/.venv/lib/python3.5/site-packages/aiohttp/protocol.py", line 387, in feed_eof
    raise errors.ContentEncodingError('deflate')
aiohttp.errors.ContentEncodingError: 400, message='deflate'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x806696470>
```

```
curl -XDELETE -v localhost:8098/buckets/ololo/keys/XXXX                                                                              
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8098 (#0)
> DELETE /buckets/ololo/keys/XXXX HTTP/1.1
> Host: localhost:8098
> User-Agent: curl/7.45.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Vary: Accept-Encoding
< Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
< Date: Tue, 02 Feb 2016 09:39:46 GMT
< Content-Type: application/json
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

```
12:43:49.902869 IP localhost.8098 > localhost.49355: Flags [P.], seq 400:425, ack 244, win 128, options [nop,nop,TS val 586110440 ecr 1045355615], length 25
E..Me.@.@...............Z..<._.).....A.....
".U.>N._..................I*.....
12:43:49.902878 IP localhost.49355 > localhost.8098: Flags [.], ack 425, win 1269, options [nop,nop,TS val 1045355616 ecr 586110440], length 0
E..4e.@.@................_.)Z..U.....(.....
>N.`".U.
12:43:49.918847 IP localhost.49355 > localhost.8098: Flags [P.], seq 244:437, ack 425, win 1275, options [nop,nop,TS val 1045355632 ecr 586110440], length 193
E...e.@.@................_.)Z..U...........
>N.p".U.DELETE /buckets/ololo/keys/XXXX HTTP/1.1
ACCEPT: */*
ACCEPT-ENCODING: gzip, deflate
HOST: 127.0.0.1:8098
USER-AGENT: Python/3.5 aiohttp/0.20.2
CONTENT-LENGTH: 0
CONNECTION: keep-alive


12:43:49.921062 IP localhost.8098 > localhost.49355: Flags [P.], seq 425:654, ack 437, win 128, options [nop,nop,TS val 586110459 ecr 1045355632], length 229
......@.@...............Z..U._.......
".U.>N.pHTTP/1.1 204 No Content
Vary: Accept-Encoding
Server: MochiWeb/1.1 WebMachine/1.10.0 (never breaks eye contact)
Date: Tue, 02 Feb 2016 09:43:49 GMT
Content-Type: application/json
Content-Length: 0
Content-Encoding: gzip


12:43:49.939182 IP localhost.49355 > localhost.8098: Flags [F.], seq 437, ack 654, win 1275, options [nop,nop,TS val 1045355653 ecr 586110459], length 0
E..4e.@.@................_..Z..:.....(.....
>N..".U.
12:43:49.939216 IP localhost.8098 > localhost.49355: Flags [.], ack 438, win 128, options [nop,nop,TS val 586110477 ecr 1045355653], length 0
E..4e.@.@...............Z..:._.......(.....
>N..
12:43:49.939352 IP localhost.8098 > localhost.49355: Flags [F.], seq 654, ack 438, win 128, options [nop,nop,TS val 586110477 ecr 1045355653], length 0
E..4e.@.@...............Z..:._.......(.....
>N..
12:43:49.939369 IP localhost.49355 > localhost.8098: Flags [.], ack 655, win 1275, options [nop,nop,TS val 1045355653 ecr 586110477], length 0
E..4e.@.@................_..Z..;.....(.....
>N..".V
```

### PR DESCRIPTION
**Pull request by asvetlov**
Fix for #758

### CODE REVIEW

**Comment by kxepal** [comment]
+1 
I had the same issue [workaround](https://github.com/aio-libs/aiocouchdb/blob/master/aiocouchdb/client.py#L44-L85). But those changes were not accepted ):

**Comment by asvetlov** [comment]
@kxepal what do you mean by _not accepted_?
@fafhrd91 rejected your PR to aiohttp about the change?
I cannot remember any issue for the problem, sorry.

**Comment by asvetlov** [comment]
Got it

**Comment by asvetlov** [comment]
See also #154

**Comment by kxepal** [comment]
Reread the backlog. "not accepted" was a bad wording, sorry, didn't remember all the details. Asked for a bit more work in addition to addressing current issue - yes, but for those cases were not in my list. Ironically, now we're almost in sync (I didn't took 304 response into account) (;

Anyway, it's good that this problem finally get fixed (: \o/

**Comment by asvetlov** [comment]
@fafhrd91 do you agree with the patch?

**Comment by fafhrd91** [comment]
+1

**Comment by asvetlov** [comment]
Done

**Pull request merged**
