### PR TITLE
Fix broken wsgi.py due to sockname info size

### PR DESCRIPTION
**Pull request by merrellb**
Addresses issue introduced by cccb9cbf267cd753c958297f6f3784d4f20799db

### CODE REVIEW

**Comment by merrellb** [comment]
This failed immediately on any request when using aiobottle.  Not sure how their codepath differs from existing wsgi tests.

**Comment by redixin** [comment]
getsockname may return more then 2 values, e.g. in case of AF_INET6 (host, port, flowinfo, scopeid)

Probably we should check the address family and call appropriate code to fill in variables.

**Comment by merrellb** [comment]
On my OSX box I do get back the four part tuple.  I can't say I am familiar with flowinfo or scopeid so it isn't clear how helpful they would be to detect and add them to the 'environ' variable.  Given the move to tuple unpacking in the earlier commit, this seemed like the quickest way to get wsgi working again :-)

**Comment by asvetlov** [comment]
I'm with @redixin 
We should explicitly process 3 address families: AF_INET, AF_INET6 and AF_UNIX without relying on presence of `peername` or length of address tuple.

**Comment by redixin** [comment]
@asvetlov I've made a patch, but it adds one extra call `get_extra_info('socket')` to query address family. The problem is this will be called at every request, but may be called once at start of the daemon. Could you please give me a glue how this can be done?

**Comment by asvetlov** [comment]
`get_extra_info(socket)` is a dictionary lookup, not a syscall.
`socket.family` is not a syscall also.
Feel free to get the info on every request.

**Comment by redixin** [comment]
@asvetlov @merrellb please take a look https://github.com/KeepSafe/aiohttp/pull/718

**Comment by asvetlov** [comment]
Fixed by #718

**Pull request closed without merging**
