### PR TITLE
#778 autoreload facility for web server

### PR DESCRIPTION
**Pull request by SergeChmelev**
## Checklist
- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes

### CODE REVIEW

**Comment by asvetlov** [comment]
Guys, do you have any plans to work on the issue?
I really appreciate your help but if  you've decided to abandon the PR please let me know -- maybe somebody or I will pickup the work.

**Comment by ohsabry** [comment]
I would find this incredibly useful. Would be happy to try and help if no one is actively working on this.

**Comment by SergeChmelev** [comment]
We definitely going to finish this, give me two weeks, please.

**Comment by asvetlov** [comment]
cool!

**Comment by fafhrd91** [comment]
close in favor of https://github.com/samuelcolvin/aiohttp-devtools

**Pull request closed without merging**
