### PR TITLE
Add recreate method to aiohttp.ClientSession().

### PR DESCRIPTION
**Pull request by AraHaan**
This allows a person to create a ``ClientSession`` that was closed without having to reinitialize a class.

There is a problem this fixes. Classes are not destructed after initialized even after the variable that the initialization goes it is overridden by another instance causing a Resource Leak until the Python interpreter is closed. This fixes that issue by explicitly adding an recreate method to eliminate the need to reinitialize the class.

## What do these changes do?

Adds a way to create a ClientSession without having to reinitialize the class causign a Resource and a Memory leak if not careful.

## Are there changes in behavior for the user?

Yes, instead of overwriting a closed Client Session Instance with a new instance they should use the new ``recreate`` method I made in this PR instead to reduce Memory and Resource leaks.

## Related issue number

#1503 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] Add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by AraHaan** [comment]
Working on docs and unit tests and all that to get all those checks done.

**Comment by AraHaan** [comment]
I am thinking that the failing tests needs some fixing. If only all tests had a logger that shows what all fails and their stack trace (if there is a traceback generated) to actually know what tests fails, is skipped, and passes by name.

**Comment by asvetlov** [comment]
aiohttp will never have hacks like this.
ClientSessions's life circle is: Init -> Use -> Close

**Comment by AraHaan** [comment]
But this does help those who do things just like discord.py does.

**Pull request closed without merging**
