### PR TITLE
Fix small typo in client documentation

### PR DESCRIPTION
**Pull request by veleritas**
## What this change does?

There was a tiny typo in the documentation for the client example. The assertion had a single equals sign instead of two.

## How to test your changes?

There was no test since I only changed the documentation file.

## Checklist

- [x] Code is written and well
- [x] Tests for the changes are provided
- [x] Documentation reflects the changes

### CODE REVIEW

**Comment by popravich** [comment]
I think you've created PR into wrong branch (0.21 instead of master)

**Comment by veleritas** [comment]
Sorry, was I supposed to create the pull request into master? The little note said to choose the latest release branch instead of master.

Do you want me to close this pull request and make another one?

**Comment by popravich** [comment]
Hmm, this is a bit confusing for me too,
@asvetlov can you clarify?

**Comment by asvetlov** [comment]
@veleritas @popravich my intention was: for small fixes
1. Clone aiohttp repo
2. Switch to 0.21 branch
3. Make a fix
4. Push commit back 
5. Make a PR for fixed 0.21 branch in clone against 0.21 branch from master.

**Comment by popravich** [comment]
Oh, ok. I think we need to explain this in CONTRIBUTING.rst or in ISSUE / PR templates

**Comment by asvetlov** [comment]
@popravich would you make docs update?

**Comment by popravich** [comment]
sure, will do

**Comment by asvetlov** [comment]
thanks

**Comment by asvetlov** [comment]
Fixed by 31c7367

**Pull request closed without merging**
