### PR TITLE
Add test for default Expect handler

### PR DESCRIPTION
**Pull request by redixin**
Server should return 417 if any of the expectations cannot be met.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.20

### CODE REVIEW

**Comment by redixin** [comment]
Currently expect handler called only if value of Expect header is "100-continue"

It would be much better if default handler could return 417 in case of unknown value of this field.

**Comment by asvetlov** [comment]
Sorry for delay.

I think the current behavior should be fixed.

Please provide a patch.

@fafhrd91 you've added support for `Expect` header. 
Do you have an objection for shrinking allowed cases?

**Comment by fafhrd91** [comment]
+1

**Comment by redixin** [comment]
I have a doubt. In fact 100-continue is only one known Expect header. This change makes code more strict but slightly harder to use.

**Comment by redixin** [comment]
@asvetlov ping

**Comment by asvetlov** [comment]
Let's postpone it until aiohttp 0.19 release

**Pull request merged**
