### PR TITLE
Don't bail out if it's a CoroWrapper

### PR DESCRIPTION
**Pull request by s0undt3ch**
## What do these changes do?

When running asyncio in debug mode, for example with the environment variable `PYTHONASYNCIODEBUG=1`, don't bail out because it does work.

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Before going through the checks, does this code please you guys?
Do this differently?

**Comment by asvetlov** [comment]
I doubt if you use custom parsers with aiohttp.
I thought to drop this assertion at all.

**Comment by fafhrd91** [comment]
I think it is ok to drop that assert

**Comment by s0undt3ch** [comment]
Want me to just update this PR with the assertion removal?

**Comment by asvetlov** [comment]
Fixed by 4b4306f

**Comment by s0undt3ch** [comment]
:+1:

**Pull request closed without merging**
