### PR TITLE
Added third party aiocache and example

### PR DESCRIPTION
**Pull request by argaen**
## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by asvetlov** [comment]
I'll love to add aiocache into third-parties list but, sorry, I don't want to include your example.
Let's keep it in aiocache itself.

P.S.
Using global dict for setting smells as anti-pattern for me.
I mean

```
aiocache.settings.set_defaults(
    cache="aiocache.RedisCache",
    namespace="test"
)
```

**Comment by argaen** [comment]
Removed the example :).

> Using global dict for setting smells as anti-pattern for me.

Its not a global dict, they are global variables of the module. I know global variables are an anti pattern but not always. By default aiocache uses Memory backend with default serializer (which does nothing) and default policy (which does nothing).

Now imagine that you want to use always Redis as your backend with a specific serializer at a given endpoint and port. With these global settings feature you just have to change 4 lines, using them explicitly you have to change them everywhere. Example:

```
cached(ttl=10) -> cached(cache=RedisCache, endpoint=foo, port=bar, serializer=blah)
```

Now imagine you have lots of instances all along your code...

If you have a better proposal about how do address this which is both clean and maintainable happy to hear! :)

**Comment by asvetlov** [comment]
I don't know how to do it in framework agnostic way but in case of aiohttp you could push global setting into `Application` object.

**Comment by argaen** [comment]
That would be a partial solution, but in the case of decorators you would still need to pass all the attributes.. =/. 

I prefer to leave it open to the developer :).

**Pull request merged**
