### PR TITLE
Fix encoding of static files

### PR DESCRIPTION
**Pull request by gladhorn**
When serving a .txt.gz file, mimetypes correctly reports encoding
'gzip'. This lets browsers treat compressed files properly.

### CODE REVIEW

**Comment by asvetlov** [comment]
Please add a test also.

**Comment by gladhorn** [comment]
Where would the test fit best? I was thinking about test_urldispatch - but there seems to be no test that actually downloads a file from the static server afaict. Should it create a file on the fly, or should I add a small .gz file?

**Comment by asvetlov** [comment]
There are functional tests for static file: https://github.com/KeepSafe/aiohttp/blob/master/tests/test_web_functional.py#L251

Please add another one for your case.
You may push tiny .gz file in ./tests folder -- we already have data files here.

**Comment by asvetlov** [comment]
Thanks for contribution!

**Pull request merged**
