### PR TITLE
Gunicorn debug mode

### PR DESCRIPTION
**Pull request by imbolc**
## What do these changes do?

It just removes `debug` setting from gunicorn worker wich cause error when it differs from `app.debug`

### CODE REVIEW

**Comment by imbolc** [comment]
Sorry, tests fixed.

**Comment by asvetlov** [comment]
Would you update CHANGES as well?

**Comment by imbolc** [comment]
Done

**Comment by asvetlov** [comment]
Looks like the robot still don't want to accept your PR :smile:

**Comment by imbolc** [comment]
Merge it, before they change their mind :)

**Pull request merged**
