### PR TITLE
Skip default headers

### PR DESCRIPTION
**Pull request by asvetlov**
Fix for #457

### CODE REVIEW

**Comment by asvetlov** [comment]
@kxepal @fafhrd91 @popravich guys, do you agree with `skip_auto_headers` parameter name?

**Comment by fafhrd91** [comment]
maybe `skip_default_headers` ? or is it really `auto` headers?

**Comment by asvetlov** [comment]
@fafhrd91 it's autogenerated headers. 
There is ambiguous for _default headers_ meaning: we have autogenerated headers and `ClientSession` headers.
Both are used if the header is not specified directly but I don't want skip session's headers by the flag -- user can just don't pass the header into `ClientSession` constructor.

**Comment by fafhrd91** [comment]
ok, then it is fine.

**Pull request merged**
