### PR TITLE
A bit more documentation fixes

### PR DESCRIPTION
**Pull request by Gennady-Andreyev**

### CODE REVIEW

**Comment by Gennady-Andreyev** [comment]
By the way, github [doesn't support API v1 or v2](https://github.com/blog/1160-github-api-v2-end-of-life) anymore, so https://github.com/timeline.json endpoint that's used in examples across the docs retied a while ago. Would it make sense to replace it with its working "heir" - https://api.github.com/events?

**Comment by asvetlov** [comment]
@Gennady-Andreyev please do replacement.

**Comment by Gennady-Andreyev** [comment]
@asvetlov , will do within this pull request!

**Comment by Gennady-Andreyev** [comment]
Done

**Comment by asvetlov** [comment]
Thanks!

**Pull request merged**
