### PR TITLE
Add easier way to Hide warnings from ClientSession

### LINKED ISSUE #1499: ClientSession is not aware of TestClient
There's a `ResourceWarning` and message per test method in `test_utils.AioHTTPTestCase`. The following produces:
```python

from aiohttp import web, test_utils

class TestCase(test_utils.AioHTTPTestCase):

    def get_app(self, loop):
        return web.Application(loop = loop)

    def test1(self):
        pass

    def test2(self):
        pass
```

` python -m unittest test`

```
aiohttp/test_utils.py:212: ResourceWarning: Creating a client session outside of coroutine is a very dangerous idea
  **kwargs)
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f5cbc921cc0>
.Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f5cbc921e48>
```

This is because `ClientSession` expects running IO loop.

Note that there's not only a warning, but also a call to `loop.call_exception_handler()` with mocked context, so this is impossible prevent this output with normal Python `warnings.filterwarnings` which is likely an warning design issue in the package. 

aiohttp 1.2.0

### PR DESCRIPTION
**Pull request by AraHaan**
Closes #1499 by allowing the end user to initialize the class with a bool to show warnings or to not show warnings.

## What do these changes do?

Allow users to easily suppress warnings after and when creating a ClientSession instance.

## Are there changes in behavior for the user?

No, just adds more control over the ClientSession instance.

## Related issue number

#1499

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] Add yourself to `CONTRIBUTORS.txt` (in #1505)
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by AraHaan** [comment]
WTH I did not close this...

**Comment by AraHaan** [comment]
got to love git command line likes to discard all my changes.

**Comment by AraHaan** [comment]
... Why is git removing all of my commits... Every time I try to squash them...

**Comment by AraHaan** [comment]
nvm going to go with a new branch on the other clone so it will work on the commit squashing and sadly a new PR.

**Comment by PaulReiber** [comment]
Mind wrapping up this thread with a note about what happened? twice?

> got to love git command like discarding all my changes.

> ... Why is git removing all of my commits...

it can potentially help others learning about git processes when we share
what happened, went sideways, etc.

thanks!

Kind regards,


*Paul Reiber*http://about.me/reiber

**Comment by AraHaan** [comment]
Well I used the git shell programs for Windows to clone it however oddly enough when I use the same commands that I use to rebase for commit squashing without using github desktop with the repo itself then the commits are oddly discarded but when cloned with that they somehow magically are not.

**Comment by PaulReiber** [comment]
Hrm... wondering if that's a bug in gitshell or a config setting somewhere?

Thanks for your note, and Happy Holidays!



Kind regards,


*Paul Reiber*http://about.me/reiber

**Pull request closed without merging**
