### PR TITLE
Accept an errors parameter for text decoding ClientResponses

### PR DESCRIPTION
**Pull request by bmuller**
## What do these changes do?

Users can now give a parameter specifying what should happen to decoding errors when asking for the `text()` from a `ClientResponse`.  This is passed directly into the [bytes() decode method](https://docs.python.org/3/library/stdtypes.html#bytearray.decode).

The internet is full of websites that have incorrectly specified their character encoding or that have one or two characters on a page that are not encoded correctly.  Right now, the `aiohttp` library just throws an exception when this happens - for a more resilient solution, users should be able to optionally provide an alternative error handling strategy for incorrectly encoded characters.

## Are there changes in behavior for the user?

Nope - just a new optional parameter.

## Related issue number

Nope.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] Add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new entry to `CHANGES.rst`
  * Choose any open position to avoid merge conflicts with other PRs.
  * Add a link to the issue you are fixing (if any) using `#issue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by fafhrd91** [comment]
Could you add test for this change?

**Comment by bmuller** [comment]
@fafhrd91 sure - what would you like to be tested though?  This is a pretty inconsequential change that just passes another optional parameter down to Python std lib call.

**Comment by fafhrd91** [comment]
test that `errors` param get passed to decode function, also could you use `errors` keyword argument for decode function.

**Comment by bmuller** [comment]
OK - let me know if there's anything else you need @fafhrd91

**Comment by fafhrd91** [comment]
great! thanks

**Pull request merged**
