### PR TITLE
Check address family to fill wsgi env properly

### PR DESCRIPTION
**Pull request by redixin**

### CODE REVIEW

**Comment by merrellb** [comment]
I must admit I don't have a good grasp of the underlying networking code.  It seems to address the immediate issue with unpacking the sockname tuple.  However in terms of equivalency to the old code.
- This commit loses the split(':')[0] on the hostname as well as the fallback to _host from the sockname.
- This commit no longer checks self.transport.get_extra_info('peername') before trying to unpack the values.  Does the family check insure that this will succeed?

**Comment by redixin** [comment]
@merrellb oh, I forgot it, thanks

**Comment by merrellb** [comment]
Cool.  So we prefer to get  SERVER_NAME and SERVER_PORT from the message rather than self.transport.get_extra_info('sockname')?

**Comment by asvetlov** [comment]
@merrellb yes, request's HOST header is the preferable source for host info.

@redixin looks good. Please fix flake8 errors.

**Comment by redixin** [comment]
@asvetlov done. Also added skipTest if no AF_UNIX (appveyor)

**Comment by asvetlov** [comment]
thanks

**Pull request merged**
