### PR TITLE
fix #1555 AioHTTPTestCase method name mistype - get_applicaion

### LINKED ISSUE #1555: AioHTTPTestCase method name mistype - get_applicaion instead of get_application
## Long story short

missed letter in word looks confusing and misleading

## Expected behaviour

method to be called get_application

## Actual behaviour

it is called get_applicaion

## Steps to reproduce

check commit by Andrew: https://github.com/KeepSafe/aiohttp/commit/8bfabd7ab25f85def9124e8a87d5681b14234afb

## Your environment
just mistype

### PR DESCRIPTION
**Pull request by jazz-jack**
## What do these changes do?

fix mistype in method name

## Are there changes in behavior for the user?

yes, it changes AioHTTPTestCase public method name

## Related issue number

#1555 

## Checklist
it is just a typo fix

### CODE REVIEW

**Comment by fafhrd91** [comment]
Good catch! Could you add old name and add deprecation warning

**Comment by jazz-jack** [comment]
i doubt anybody used it, the issue is quite obvious
1-month old bug, not released...
i'd prefer to keep sources cleaner and just leave it

**Comment by fafhrd91** [comment]
good

**Comment by fafhrd91** [comment]
thanks!

**Pull request merged**
