### PR TITLE
If send fails, websocket is not closed

### PR DESCRIPTION
**Pull request by MarcoSulla**
The WebSocketResponse has a _conn_lost attribute that is not augmented if the asyncio's writer does fail to send data. I added a patch, but IMHO asyncio should raise an error instead of logging a simple warning.

### CODE REVIEW

**Comment by Marco-Sulla** [comment]
Furthermore, I think `ConnectionResetError` should be raised, not `RuntimeError`.

PS: Travis check fails because of W293. I hope you could ignore that warning.

**Comment by Marco-Sulla** [comment]
Excuse me, why you closed it?

**Comment by asvetlov** [comment]
Hmm, github has closed the issue because I've deleted 0.21 branch :(

**Comment by asvetlov** [comment]
After thinking on your patch I cannot accept it, sorry.
`self._writer._conn_lost` is very private api, say uvloop doesn't support it.

Regarding to changing from `RuntimeError` to `ConnectionResetError` -- the last assumes that `errno` code is `ECONNRESET` which is not true for our case.
Using `aiohttp.ClientDisconnectedError` makes more sense.

**Comment by asvetlov** [comment]
What's wrong with current implementation?
You'll get disconnection error on next loop iteration, isn't it?

**Comment by Marco-Sulla** [comment]
No errors, I get warnings from `asyncio` and websocket is never closed.

What about this?

```
    def check_con(self):
        conn_lost_tot = self._conn_lost + self._writer._conn_lost

        if conn_lost_tot >= THRESHOLD_CONNLOST_ACCESS:
            raise RuntimeError('WebSocket connection is closed.')
```

**Comment by asvetlov** [comment]
Sorry for late answer.
Say again, `self._writer._conn_lost` is not public API, we shouldn't rely on it.
E.g. it's not exposed by uvloop IFAIK.

**Pull request closed without merging**
