### PR TITLE
request.json() now returns empty dict when no data

### PR DESCRIPTION
**Pull request by bmwant21**
There was ValueError raising when trying to access request.json() is there is no data. I think that this is incorrect behavior and empty dict (or something else) must be returned in this case.

### CODE REVIEW

**Comment by asvetlov** [comment]
I think ValueError is correct behavior.

Standard `json` module also doesn't implicitly convert empty string into empty dict:

```
>>> from json import loads
>>> loads('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
>>> loads(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'
>>> 
```

**Comment by ludovic-gasc** [comment]
+1 to keep ValueError behaviour.

**Comment by bmwant** [comment]
Ok, but why in get/post cases you get empty dict <_MultiDictProxy {}> and have to catch ValueError in json-context? What's the point? Just json-module convention or something else?

```
@asyncio.coroutine
def get_data_from_post(request):
    data_post = yield from request.post()
    print(data_post)
    return web.Response(body='The response post'.encode('utf-8'))


@asyncio.coroutine
def get_data_from_get(request):
    print(request.GET)
    return web.Response(body='The response from get'.encode('utf-8'))


@asyncio.coroutine
def get_json(request):
    try:
        data_json = yield from request.json()
    except ValueError:
        return web.Response(body='No json-data'.encode('utf-8'))
    return web.Response(body='The response'.encode('utf-8'))
```

**Comment by asvetlov** [comment]
I think GET and POST are user for checking for key presence. Empty dict is pretty good sign for _item not present_ message.
JSON has another behavior: it is either json-encoded or not. Arbitrary data is not JSON.

**Pull request closed without merging**
