### PR TITLE
Compose middleware only once.

### PR DESCRIPTION
**Pull request by alexsdutton**
Should be more efficient, and means that middleware factories can hook in signal handlers
for processing responses in a guaranteed order (once we have signals, of
course).

### CODE REVIEW

**Comment by asvetlov** [comment]
I don't follow how signals can help?

**Comment by alexdutton** [comment]
Ah, sorry. I was thinking it would help people that want to connect response_prepare signals in the same order that they've arranged their middleware. You'd have something like:

```
@asyncio.coroutine
def middleware_factory(app, handler):
    app.on_response_prepare.append(do_something)
    @asyncio.coroutine
    def middleware(request):
         …
         return (yield from handler(request))
    return middleware
```

At the moment, middleware_factory is called once per request, which means it can't be used to do this kind of thing, leading to one having to plug in the signal handler separately, keeping the orders in sync if you move any of them around.

**Comment by asvetlov** [comment]
People should subscribe for signal not in middleware but on application setup stage.

Something like `library.setup(app)` for both adding middlewares and subscribing for signals.
Appending new signal handler on every middleware request makes a mess (should I describe why?).

Is it makes a sense?

**Comment by asvetlov** [comment]
Your PR looks like optimization (I don't know how it affects aiohttp performance).
But I want to make nested sub-application support sometimes.
App should pass request to sub-app on route match and sub-app will apply request according own signal handlers and middlewares.
I don't know how implement it right now but I have strong feeling the change makes sense.

**Comment by alexdutton** [comment]
nested sub-applications, as in nesting routers? Sounds reasonable to me. I did play with a Host-based router at one point, but had trouble with making reverse lookups on routes work in an elegant way (i.e. `request.app.router['routename'].url()`).

Shall I profile the proposed change to see how useful it actually is, or perhaps look at the sub-app/route issue?

**Comment by asvetlov** [comment]
That's up to you. Personally I curious about speed improvement after your change.
We can commit it now if value matters.

Subapp support is a next big rock after signals, requires non-trivial changes.

**Comment by asvetlov** [comment]
Close as nested apps are incompatible with PR.
Feel free to reimplement it on top of current code but please make boost measure.

**Pull request closed without merging**
