### PR TITLE
Ignore 304/204 response body

### LINKED ISSUE #505: Client use aiohttp, will be hang up ,when server return 304
As http rfc2616( http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html):
4.4 Message Length
    1.Any response message which "MUST NOT" include a message-body (such as the 1xx, 204, and 304 responses and any response to a HEAD request) is always terminated by the first empty line after the header fields, regardless of the entity-header fields present in the message.

So, server return 304 without content-length header .but aiohttp client will waiting for content-length.

### PR DESCRIPTION
**Pull request by carlcarl**
Fix #505

### CODE REVIEW

**Comment by asvetlov** [comment]
Please rewrite tests to use `test_client_functional_newstyle.py` not `test_client_functional.py`

**Comment by carlcarl** [comment]
Oh, didn't notice that.
So all the tests should be moved to `test_client_functional_newstyle.py` in the future?

**Comment by asvetlov** [comment]
Yes. I even plan to rewrite these in py.test style but as first step I want to get rid of test_utils server.

**Comment by carlcarl** [comment]
Done.

**Comment by asvetlov** [comment]
Thanks

**Pull request merged**
