### PR TITLE
Fix StreamResponse output_length typo.

### PR DESCRIPTION
**Pull request by hellysmile**
Just small typo fix

### CODE REVIEW

**Comment by rutsky** [comment]
@hellysmile thanks!

Can you add small test for this? E.g. similar to [this one](https://github.com/KeepSafe/aiohttp/blob/master/tests/test_web_response.py#L895).

**Comment by hellysmile** [comment]
@rutsky done!

**Comment by rutsky** [comment]
Thanks! LGTM.

**Comment by asvetlov** [comment]
Thaks! Merged.

**Pull request merged**
