### PR TITLE
Supoort py3 wheels

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
This will also require adding "bdist_wheel" when you do your package upload

**Comment by asvetlov** [comment]
aiohttp has C extensions (Cython ones actually).
Thus wheels should be platform specific: Windows 32/64, MacOSX etc.
For Linux situation is worse: wheel should depend on linux distribution but there is no linux distribution tag in wheel format.

Long story short: for libraries with C extensions only windows wheels make sense, all other platforms should be rebuilt from sources. But I'm too lazy yet for setting up it sinse aiohttp may work without compiled extensions.

**Comment by graingert** [comment]
right it might be an idea to split the C extensions out into a dependant package

**Comment by asvetlov** [comment]
Why? Keeping extensions in separate package over-complicates development and deployment without any effort.
Installing source tar.gz is not very different from pure-python wheel.

**Comment by graingert** [comment]
I guess so

**Pull request closed without merging**
